config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'teachers/index'

  devise_for :users

  get 'guests/index'
  get 'guests/about'
  get 'guests/help'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  #----- courses ----
  get '/courses/filter', to: 'courses#filter', as: 'filter_list'
  get '/courses/search', to: 'courses#search', as: 'search_courses'
  get '/courses/enrollment/:id', to: 'courses#enrollment', as: 'enrollment'
  resources :courses

  #----- student_courses ---
  get '/student_courses/search',to: 'student_courses#search', as: 'search_student_course'
  resources :student_courses
 
  #----- Enrolled users/students ----
  resources :enrolled
  patch '/enrolled/:id', to: 'enrolled#update', as: 'update_enrolled'

  #----- Excusions ------
  resources :excursions

  #------ Student Excursions -----
  resources :student_excursions

  #------ Student Groups ----
  resources :student_groups
  patch '/student_group/:id', to: 'student_groups#update', as: 'update_student_group'

  #------ passengers ------
  resources :passengers

  root "guests#index"
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_students

    
    def index

    end
    #display search field to search for course.
    # search by I.D given by teacher.
    # search by Name given by teacher.
    # search by Teacher's name.
    def search
        #return all active courses if query input is null
        if params[:query] == ""
            @courses = Course.where(active: true)
        elsif !"#{params[:query]}".match?(/\D+/)
            @courses = []
            @courses =  Course.where(id: params[:query].to_i, active: true)
        elsif params[:query].match?(/@/)
            teacher = User.where(email: params[:query]).first
            @courses = Course.where("name LIKE?", "%#{params[:query]}%", active: true)
        elsif params[:query].length > 0
            @courses = Course.where(name: params[:query],active: true)
        end
    
        #nothing found, redirect to student index with alert message.
        if @courses.length == 0
            
            redirect_to students_index_path, alert: "Nothing found"
        end
    end

    # student enrolls into a course.
    # Model: Enrollment
    # it takes: - user_id
    #           - course_id
    def show
        @course = Course.find(params[:id])
        @excursions = @course.excursions
        if(current_user != nil)
            if @course.enrollments.where(user_id: current_user.id).length==0
                Enrollment.create(user_id: current_user.id, course_id: @course.id,banned: false)
            end
        end    
    end

    # User course.id and current_user.id to find the enrollment.id.
    # user the enrollment.id to remove the enrollment from the table.
    def destroy
        @enrollment= Enrollment.where(course_id: params[:id],user_id: current_user.id).first
        
        if @enrollment.destroy
            redirect_to root_path, status: 303, data: {turbo_method: :get}
        end
        
    end
    

    private

    def only_students
      if current_user.role != 1
        redirect_to root_path
      end
    end
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/views/student_courses/_course.html.erb
<li style="list-style-type: none">

<div class="card my-2">
    <div class="card-header">
        <div class="fs-2"><%= course.name %><span class="fs-6 ms-2">(Course ID: <%= course.id %>)</span></div>
    </div>
  
    <div class="card-body">
        <h5 class="card-title">Cohort: <%= course.year %>/<%= course.month %></h5>
    <p class="card-text">Description: <%= course.description %></p>
    <% if Course.find(course.id).enrollments.where(user_id: current_user.id).length == 0%>
        <%= link_to "Join Course", student_course_path(course.id),class: "btn btn-primary"%>
    <% else %>
        <%= link_to "Go to Course", student_course_path(course.id), class: "btn btn-success"%> All enrolled
    <% end %>
  </div>
</div>



</li>

app/views/student_courses/index.html.erb
<main class="container">
    <h1>Search Course by using:</h1>
    <ul>
        <li>Course Name </li>
        <li>Course I.D given by your teacher </li>
        <li>Teacher's email address </li>
    </ul>
    <div class ="col-sm-6">
    
        <%= form_with url:"/student_courses/search", method: :get  do |form | %>
            <%= form.label :query, "Search for:" %>
            <%= form.search_field :query %>
            <span lass="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Course Name">
            <%= form.submit "Search" %>
            </span>
        <% end %>
       
       
        <p class="alert"><%= alert %></p>
        <p class="notice"><%= notice %></p>
       
       
    </div>
</main>

app/views/student_courses/search.html.erb
<main class="container">
<%= turbo_frame_tag "courses_result" do%>
<h1>Searched <%= pluralize(@courses.length, 'Course')%> </h1>
 <p class="alert"><%= alert %></p>
 <p class="notice"><%= notice %></p>
<div class="overflow-scroll h-75">
<ul class= "col-sm-8 mx-auto">
<%= render partial: "student_courses/course", collection: @courses %>
</ul>
</div>
<% end %>
</main>

app/views/student_courses/show.html.erb
<%= turbo_frame_tag "courses_result" do%>

<main class="container d-flex flex-row">
    <section class="col-sm-6 px-2 border">
        <h5>Course Name: <%= @course.name %></h5>
        <p>Course ID: <%= @course.id %></p>
        <p>Cohort: <%= @course.year%>/<%= @course.month%></p>
        <p>Description</p>
        <p class="border" style="height: 100px"><%= @course.description%></p>
        <p>Active: 
        <% if @course.active %>
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="blue" class="bi bi-check2-square" viewBox="0 0 16 16">
                <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
            </svg>
        <%else%>
        <i class="bi bi-check"></i>
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-x-square" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
            </svg>
        <% end %>
        </p>
        <div class="border overflow-scroll" style="height: 300px">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Arrival Time</th>
                    <th scope="col">Description</th>
                    <th scope="col">Address</th>
                    <th scope="col">Link</th>
                </tr>
            </thead>
            <tbody>
                <% @excursions.each do |excursion|%>
                    <tr>
                        <td><%= excursion.name%></td>
                        <td><%= excursion.arrive_time%></td>
                        <td><%= excursion.description%></td>
                        <td><%= excursion.street_name%> <%= excursion.suburb%> <%=excursion.city%> <%=excursion.state%> <%=excursion.post_code%></td>
                        <td><%=link_to "more info", student_excursion_path(excursion.id), data: {turbo_frame: "student_excursion"}%></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        </div>
        
        <%= link_to "Leave Course", student_course_path(@course.id), data: { turbo_method: :delete},class: "btn btn-primary" %>
    </section>

    <section class="col-sm-6 px-2 border">
        <%= turbo_frame_tag "student_excursion" do %>

        <% end %>
    </section>
</main>
<% end %>