config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'teachers/index'

  devise_for :users

  get 'guests/index'
  get 'guests/about'
  get 'guests/help'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  #----- courses ----
  get '/courses/filter', to: 'courses#filter', as: 'filter_list'
  get '/courses/search', to: 'courses#search', as: 'search_courses'
  get '/courses/enrollment/:id', to: 'courses#enrollment', as: 'enrollment'
  resources :courses

  #----- student_courses ---
  get '/student_courses/search',to: 'student_courses#search', as: 'search_student_course'
  resources :student_courses
 
  #----- Enrolled users/students ----
  resources :enrolled
  patch '/enrolled/:id', to: 'enrolled#update', as: 'update_enrolled'

  #----- Excusions ------
  resources :excursions

  #------ Student Excursions -----
  resources :student_excursions

  #------ Student Groups ----
  resources :student_groups
  patch '/student_group/:id', to: 'student_groups#update', as: 'update_student_group'

  #------ passengers ------
  resources :passengers

  root "guests#index"
end

app/controllers/student_excursions_controller.rb
class StudentExcursionsController < ApplicationController
    before_action :authenticate_user!


    def show
        #an excursion ID is passed in.
        @excursion = Excursion.find(params[:id])
        #all the groups created for this excursion is needed.
        @groups = @excursion.groups


        # the below is to build logic in the font end cleaner.
        # the logic is for displaying the appropriate buttons in the table or page.
        #----------------------------------------------------------------
        
        #see if the current user has created a group related to this excursion.
        #if the result returns an array of length greater than 0. It means he/she is a driver.
        if 0 < Group.where(user_id: current_user,excursion_id: params[:id]).length
            @is_a_driver = true
        else
            @is_a_driver = false
        end

        #Get all the passengers in this excursion where it is equal to the current user.
        # If the length of the array is greater than 0 then he/she is a passenger.
        if @excursion.passengers.where(user_id: current_user).length >0
            @is_a_passenger = true
        else
            @is_a_passenger = false
        end       
    end
end

app/helpers/student_excursions_helper.rb
module StudentExcursionsHelper
end

app/views/student_excursions/show.html.erb
<%= turbo_frame_tag "student_excursion" do %>
    <!--shouw excursion and its details such as students and groups-->
    <h5>Excursion Name: <%= @excursion.name%></h5>
     <%= image_tag(@excursion.image, style: "width: 150px;") if @excursion.image.attached?%>
    <p class="border">Description: <%=@excursion.description%><p>
    <p>Address: <%= @excursion.street_number%> <%= @excursion.street_name%>, <%= @excursion.suburb%> <%= @excursion.city%>, <%= @excursion.state%> <%= @excursion.post_code%> </p>
    <p class="alert text-danger"><%= alert %></p>
    <p class="notice text-success"><%= notice %></p>


    <div class="border overflow-scroll" style="height: 350px">
        <table class="table table-striped">
                    <th scope="col">Pick Up Point   </th>
                    <th scrope="col">Description</th>
                    <th scope="col">Driver</th>
                    <th scope="col">Total Cost</th>
                    <th scope="col">Passenger Number</th>
                    <th scope="col">Edit Group </th>
                </tr>
            </thead>
            <tbody>
            <% @groups.each do |group|%>
                <tr>
                    <td><%= group.suburb %></td>
                    <td><%= group.description%></td>
                    <td>
                        <%= image_tag User.find(group.user_id).image, style: "with: 50px; height: 50px"  if User.find(group.user_id).image.attached?%>
                        <%= User.find(group.user_id).user_name %>
                    </td>
                    <td><%= number_to_currency(group.total_cost.to_f/100)%></td>
                    <% no_of_passengers = Group.find(group.id).passengers.length %>
                    <td><%= no_of_passengers%>/<%= group.passenger_no %></td>
                    <!--if current user created this group then display edit, where he/she can edit car capacity and pick up area.-->
                    <!--if not a driver and not a passenger in this excursion, then a Join button is shown.-->
                    <!--if no of passengers is less than the group capacity the a join button is show-->
                    <!--if the max capacity is reached, then a full button is shown. -->
                    <%if current_user.id == group.user_id %>
                        <td><%= link_to "Edit", edit_student_group_path(excursion_id: @excursion.id,id:group.id), class: "btn btn-primary" %></td>
                    <%elsif !@is_a_driver && !@is_a_passenger%>
                        <%if no_of_passengers < group.passenger_no%>
                            <td> <%= link_to "Join",  new_passenger_path(group: group.id), data: {turbo_frame: "student_excursion"},class: "btn btn-primary"%></td>
                        <% else%>
                           <td> <div class="btn btn-danger">Full</div></td>
                        <% end %>
                    <% elsif Group.find(group.id).passengers.where(user_id: current_user.id).first%>
                        <td> <%= link_to "Open", passenger_path(group.id),data: {turbo_frame: "student_excursion"}, class: "btn btn-primary" %></td>
                    <% end %>
                </tr>
            <% end%>

            </tbody>
        </table>
    </div>
    <!--if user is not a driver and not a passenger in the excursion, then he/she can create a group.-->
    <% if !@is_a_driver && !@is_a_passenger %>
        <%= link_to "Create Group", new_student_group_path(excursion_id: @excursion.id), data: {turbo_frame: "student_excursion"},class: "btn btn-primary"%>
    <% end %>
<% end %>