config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'teachers/index'

  devise_for :users

  get 'guests/index'
  get 'guests/about'
  get 'guests/help'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  #----- courses ----
  get '/courses/filter', to: 'courses#filter', as: 'filter_list'
  get '/courses/search', to: 'courses#search', as: 'search_courses'
  get '/courses/enrollment/:id', to: 'courses#enrollment', as: 'enrollment'
  resources :courses

  #----- student_courses ---
  get '/student_courses/search',to: 'student_courses#search', as: 'search_student_course'
  resources :student_courses
 
  #----- Enrolled users/students ----
  resources :enrolled
  patch '/enrolled/:id', to: 'enrolled#update', as: 'update_enrolled'

  #----- Excusions ------
  resources :excursions

  #------ Student Excursions -----
  resources :student_excursions

  #------ Student Groups ----
  resources :student_groups
  patch '/student_group/:id', to: 'student_groups#update', as: 'update_student_group'

  #------ passengers ------
  resources :passengers

  root "guests#index"
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  before_action :only_teachers
  
  def index
    @courses = Course.where(user_id: @current_user, active: true)
  end

  
  private
  def only_teachers
    if current_user == nil
      redirect_to root_path
    elsif current_user.role != 2
      redirect_to root_path
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_course.html.erb
<%= link_to course_path(course), data: {turbo_frame: "teacher_course_show"} do %>
<li class="list-group-item"> 
    <%= course.name %> 
    <%= course.year %>/<%= course.month %>
</li>

<% end %>

app/views/teachers/index.html.erb
<main class="container">

    <div class ="col-sm-6 mx-auto">
        <%= form_with url: "/courses/search", data: {turbo_frame: "courses_result"}, method: :get  do |form | %>
            <%= form.search_field :query, class: "col-sm-6 mt-5" %>
            <%= form.submit "Search", class:"btn btn-primary" %>
        <% end %>
        <div class="row col-sm-8 mt-2">
        <%= link_to "New Course",new_course_path, data:{turbo_frame: "courses_result"},class: "btn btn-primary col-sm-4 ms-auto me-3"%>
        </div>
    </div>
  
    <%= turbo_frame_tag "courses_result" do%>
        
    <% end %>

</main>