config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'teachers/index'

  devise_for :users

  get 'guests/index'
  get 'guests/about'
  get 'guests/help'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  #----- courses ----
  get '/courses/filter', to: 'courses#filter', as: 'filter_list'
  get '/courses/search', to: 'courses#search', as: 'search_courses'
  get '/courses/enrollment/:id', to: 'courses#enrollment', as: 'enrollment'
  resources :courses

  #----- student_courses ---
  get '/student_courses/search',to: 'student_courses#search', as: 'search_student_course'
  resources :student_courses
 
  #----- Enrolled users/students ----
  resources :enrolled
  patch '/enrolled/:id', to: 'enrolled#update', as: 'update_enrolled'

  #----- Excusions ------
  resources :excursions

  #------ Student Excursions -----
  resources :student_excursions

  #------ Student Groups ----
  resources :student_groups
  patch '/student_group/:id', to: 'student_groups#update', as: 'update_student_group'

  #------ passengers ------
  resources :passengers

  root "guests#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
# Only be accessed by the appropriate user.
    before_action :authenticate_user!
    before_action :only_teachers

    def index
        @courses = Course.all
    end

    def search
        # serach by id and only select those that belongs to the current user.
        #list all active courses on top of the list first.
        if !params[:query].match?(/\D+/)
            @courses = []
            @courses =  Course.where(id: params[:query].to_i, user_id: current_user).order(active: :desc)
        else
        # search by course name
            @courses = Course.where("name LIKE?", "%#{params[:query]}%")
        end
       
        # if the search returns nothing, it will list all the courses that was created by the current user.
        if @courses.length == 0
            @courses = Course.where(user_id: current_user)
        end
    end


    def filter
        # get courses that was created by the current user and order it by name.
        @courses = Course.where(user_id: current_user.id).order('name')
    end

    def show
        #user will select a course to analyse.
        @course = Course.find(params[:id])
        #since this app tries to be a single page app.
        #students enrolled into the course will be shown.
        #excursion that was created within this course is shown on the page.
        @enrollments = @course.enrollments
        @excursions = @course.excursions
    end

    def edit
        #user will select a course the view will pass the course_id to edit.
        @course = Course.find(params[:id])
    end

    def update
        #after the update button is clicked
        #find a course.
        @course = Course.find(params[:id])
        new_name = course_params[:name]

        # check if a course name is already created by current_user.
        #find the existing name in the database.
        #if the course.id in the edit is different to the course.id that was searched by name
        # then the course name is not valid.
        existing_name = Course.where(name: new_name).first
      
        if params[:id].to_i != existing_name.id.to_i
            redirect_to edit_course_path(params[:id]), alert: 'You already have created a course after this name. Choose another'
        else
            @course.update(course_params)
            redirect_to course_path(params[:id])
        end
    end

    def new
        #inform the form that it will be a create/new button
        @course = Course.new
    end

    def enrollment
        #user will choose a student, the link_to will pass a User/Student id.
        # This student ID will be used to retrieve the enrollment of the student
        # The teacher can now edit the student's enrollment status on the view.
        @enrollment = Enrollment.find(params[:id])
    end

    def create
        @course = Course.new(course_params)
        
        # check if a course name is already created by current_user.
        # if name already exist, it will return an array greater than 0.
        # then the app will be redirected to the edit page with an alert.
        # if no name is the same. Update may proceed because array length will be 0.

        if Course.where(name: @course.name, user_id: current_user.id).length > 0
            redirect_to new_course_path, alert: 'You have created a course after this name. Choose another'
        else
            @course.save
            redirect_to course_path(@course.id)
        end
    end

    def destroy
        @course = Course.find(params[:id])
        course_id = params[:id]
        # A course can only be deleted if there is no student.
        # Check if the course have students.
        # If there is. Redirect with an alert.
        # status 303 must be introduced to change turbo_stream from destoy to get.
        if @course.users.length > 0
            redirect_to courses_path, status: 303, data: {turbo_method: :get},alert: "Can not delete course because there are students in the course. You can make it in active."
        else
            @course.destroy
            redirect_to root_path, status: 303,data: {turbo_method: :get}
            
        end
    end
    

    private

    def only_teachers
        if current_user.role ==2 ||params[:id] == nil
            
        elsif current_user.role!=2 || current_user.id != Course.find(params[:id].to_i).user_id
            redirect_to root_path, alert: "You are not authorized"
        end
    end

    def show_params
        params.require(:course).permit(:id)
    end

    def course_params
        params.require(:course).permit(:name,:description,:year,:month,:active,:user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<li style="list-style-type: none">

<div class="card my-2">
    <div class="card-header">
        <div class="fs-2"><%= course.name %><span class="fs-6 ms-2">(Course ID: <%= course.id %>)</span></div>
    </div>
  
    <div class="card-body">
        <h5 class="card-title">Cohort: <%= course.year %>/<%= course.month %></h5>
    <p class="card-text">Description: <%= course.description %></p>
    <!--style button for active and non active courses. -->
    <% if course.active%>
        <%= link_to "Analyse Course", course_path(course.id),data: {turbo_frame: "courses_result" }, class: "btn btn-primary"%>
    <% else %>
        <%= link_to "Analyse Course", course_path(course.id), data: {turbo_frame: "courses_result"}, class: "btn btn-secondary"%> Non-Active
    <% end %>
  </div>
</div>



</li>

app/views/courses/_excursion.html.erb
<% excursions.each do |excursion| %>
<tr>
    <td><%= excursion.name %></td>
    <td><%= excursion.description %></td>
    <td><%= excursion.arrive_time.to_fs(:short)%></td>
    <td><%= excursion.street_number %> <%= excursion.street_name%> <%= excursion.suburb%> <%= excursion.state%> <%= excursion.post_code%>
    <td><%= link_to "edit details", edit_excursion_path(excursion.id), data: {turbo_frame: "courses_result"} %></td>
</tr>
<% end %>

app/views/courses/_form.html.erb
<!--future refactoring -->

app/views/courses/_student.html.erb
<% #make a student card to display the following %>
<% # user_name, email, banned? %>

<% enrollments.each do |enrollment| %>
<!-- style row colour, if user is banned, highlight row red.-->
<%if enrollment.banned%>
<tr class="table-danger">
<%else%>
<tr>
<% end %>
    <td><%= enrollment.user.user_name %></td>
    <td><%= enrollment.user.email %></td>
    <td><%= link_to "edit details", edit_enrolled_path(enrollment.id) %></td>
</tr>
<% end %>

app/views/courses/edit.html.erb
<%= turbo_frame_tag "courses_result" do %>
    <p class="alert text-danger"><%= alert %></p>  
    <%= form_with model: @course  do |form| %>
        <section class="d-flex flex-row">
           
           <div class="col-6">
            <h4> Edit Course </h4>
            <div class="mb-2 row">
                <%= form.label :name, class:"col-sm-2 col-form-label"%>
                <div class="col-sm-10">
                    <%= form.text_field :name, class: "form-control"%>
                </div>
            </div>
            <div class="mb-2 row">
                <%= form.label :year, class:"col-sm-2 col-form-label"%>
                <div class="col-sm-10">
                    <%= form.number_field :year, class: "form-control" %>
                </div>
            </div>
            <div class="mb-2 row">
                <%= form.label :month, class:"col-sm-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= form.number_field :month, class: "form-control" %>
                </div>
            </div>
            <div class="mb-2 row">
                <%= form.label :active, class: "col-sm-2 col-form-label"%>
                <div class="col-sm-10">
                    <%= form.check_box :active, class:"form-check-input mt-1" %>
                </div>
            </div>
           </div>

           <div class="col-6 px-1">
            <%= form.label :description, class:"col-form-label"%>
            <%= form.text_area :description, class:"form-control" %>
            <div class="row">
                <%= form.submit class:"btn btn-primary col-sm-4 ms-5 mt-3"%>
                <%= link_to "Cancel", course_path(@course.id), class: "btn btn-primary col-sm-4 ms-5 mt-3" %>
            </div>
           </div>
        </section>
    <% end %>
<% end %>

app/views/courses/enrollment.html.erb
<h3>User Name: <%= @enrollment.user.user_name %></h1>
<h2>Email: <%= @enrollment.user.email %></h2>
<%= @enrollment.id%>
<%= form_with model: @enrollment do |form|%>
    <%= form.label :active %>
    <%= form.check_box :active %>
    <%= form.submit %>
<% end %>

app/views/courses/filter.html.erb
<ul>
    <% @courses.each do |course|%>
        <li> <%= course.name %> </li>
    <% end %>
</ul>

app/views/courses/index.html.erb
<%=turbo_frame_tag "courses_result" do %>
    

<main class="container">
    <p class="alert text-danger"><%= alert %></p>
    <p class="notice"><%= notice %></p>
</main>


<% end %>

app/views/courses/new.html.erb
<%= turbo_frame_tag "courses_result" do %>
<main class="col-sm-8 mx-auto mt-5"> 
<p class="alert text-danger"><%= alert %></p>   
    <%= form_with model: @course do |form| %>
        <section class="d-flex flex-row">
           <div class="col-6">
            <h4> New Course </h4>
            
            <div class="mb-2 row">
                <%= form.label :name, class:"col-sm-2 col-form-label"%>
                <div class="col-sm-10">
                    <%= form.text_field :name, required: true,class: "form-control"%>
                </div>
            </div>
            <div class="mb-2 row">
                <%= form.label :year, class:"col-sm-2 col-form-label"%>
                <div class="col-sm-10">
                    <%= form.number_field :year, required: true,class: "form-control" %>
                </div>
            </div>
            <div class="mb-2 row">
                <%= form.label :month, class:"col-sm-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= form.number_field :month,min: 1, max: 12, required: true,class: "form-control" %>
                </div>
            </div>
            <div class="mb-2 row">
                <%= form.label :active, class: "col-sm-2 col-form-label"%>
                <div class="col-sm-10">
                    <%= form.check_box :active, checked: true, class:"form-check-input mt-1" %>
                </div>
            </div>
           </div>

           <div class="col-6 px-1">
            <%= form.label :description, class:"col-form-label"%>
            <%= form.text_area :description, class:"form-control" %>
            <div class="row">
                <%= form.submit class:"btn btn-primary col-sm-4 ms-5 mt-3"%>
                <%= link_to "Cancel", root_path, class: "btn btn-primary col-sm-4 ms-5 mt-3" %>
            </div>
           </div>
           <%= form.hidden_field :user_id, :value => current_user.id %>
        </section>
    <% end %>
</main>
<% end %>

app/views/courses/search.html.erb
<%= turbo_frame_tag "courses_result" do %>
<h1>Searched <%= pluralize(@courses.length, 'Course')%></h1>
<div class="overflow-scroll" style="height: 80%">
    <%= render partial: "courses/course", collection: @courses %>
</div>
<% end %>

app/views/courses/show.html.erb
<%= turbo_frame_tag "courses_result" do%>
<main class="border mt-3 px-2 d-flex">
<!-- Course details -->
<section class="col-sm-6 pe-2">
<h5>Course Name: <%= @course.name %></h5>
<p>Course ID:<%= @course.id %></p>
<p>Cohort: <%= @course.year %>/<%= @course.month %></p>
<p>Description</p>
<p class="h-25 border"><%= @course.description %></p>
<p>Active: 
<!--a tick icon if course is active-->
<!--a cross icon red color if course is inactive-->
<% if @course.active %>
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="blue" class="bi bi-check2-square" viewBox="0 0 16 16">
  <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
  <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
</svg>
</svg>
<%else%>
<i class="bi bi-check"></i>
   <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-x-square" viewBox="0 0 16 16">
  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
</svg>
<% end %>
</p>

<%= link_to "Edit", edit_course_path, class: "btn btn-primary col-sm-2" %>
<%= link_to "Delete", course_path(@course.id),data: {turbo_method: :delete}, class: "btn btn-primary col-sm-5 ms-1"%>

</section>

<section class="col-sm-6 px-2">
<!-- List students -->
<h5><%= pluralize(@enrollments.length, 'Student')%> joined this course</h5>

<div class="overflow-scroll" style="height: 180px">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">User Name</th>
      <th scope="col">Email</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "courses/student", locals: {enrollments: @enrollments} %>
  </tbody>
</table>
</div>

<hr>

<!-- List Excursions -->

<h5><%= pluralize(@excursions.length, 'Excursion')%> found</h5>
<%= link_to "New Excursion", new_excursion_path(course_id: @course.id),class: "btn btn-primary"%>
<div class="overflow-scroll" style="height: 280px">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Arrive Time</th>
      <th scope="col">Address</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <%= render partial: "courses/excursion", locals: {excursions: @excursions} %>
</table>
</div>
</section>
</main>
<% end %>